# Permalinks
permalink: pretty

# Setup
title: Docs Assembler demo guides
markdown_ext: markdown,tsfrg,md

# Plugins
plugins:
  - jekyll-relative-links

# Optional: configure relative_links (these are the defaults)
relative_links:
  enabled: true
  collections: true
  # Explicitly include your custom extensions
  extensions: [".md", ".markdown", ".tsfrg"]

# Disable all caching
disable_disk_cache: true

# Or more specific cache controls
full_rebuild: true



