#remote_theme: LeakyAbstractions/pretty-docs
theme: jekyll-theme-minimal
title: HAL Robotics Framework Tutorials
description: Learn how to use the HAL Robotics Framework.
logo: /assets/images/LogoDocs.PNG
show_downloads: false
github:
  is_project_page: false

#
# Default values
#
#defaults:
#  -
#    scope:
#      path: ""
#      type: doc
#    values:
#      layout: doc
#      color: blue
#  -
#    scope:
#      path: ""
#      type: pages
#    values:
#      layout: doc
#      color: blue